 
const {
  REACT_APP_AUTHOR_ID,
  REACT_APP_API_BASE_URL,
  REACT_APP_API_PRODUCTS_URL,
} = process.env;

export const API_VALUES = {
  AUTHOR_ID: REACT_APP_AUTHOR_ID,
  BASE_URL: REACT_APP_API_BASE_URL,
  PRODUCTS_URL: REACT_APP_API_PRODUCTS_URL,
};
